buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
dynamicRoutes:
  # This is a rewrite because the status code is 200. It also takes advantage of built-in splat support.
  -
    from: /grey/*
    to: /gray/:splat
    status: 200
  -
    from: /simulated-prefix/*
    to: /:splat
    status: 200
  -
    from: /gray/*
    to: /:splat
    status: 200

  # This is a custom redirect because the status code is 3xx.
staticRoutes:
  -
    from: /grey-redirect
    to: /gray
    status: 308
  -
    from: /test-redirect
    to: https://www.google.com
    status: 301
# adds authentication to your site. Commented out as a policy with the name auth02 must exist
# authentication:
#   policyName: auth02
#   includePaths:
#     - /red # red is locked down

