buildConfiguration:
  buildCommand: npm run build:local
  installDependenciesStep:
    command: npm install
    requiredFiles:
      - package.json
      - package-lock.json
      - .npmrc
# adds authentication to your site. Commented out as a policy with the name auth02 must exist
authentication:
  policyName: auth-policy2

